### ISSUE TITLE
The commit 8b20c1510ffc64fa22db127570e3c512449f12ae includes regression for TableRow management

### ISSUE THREAD

**Issue by Kyoku57** [verronpro/docx-stamper#113]
**Describe the bug**
Regression with tablerow management. The iterable data are put at the end of a Table even if there is no iterable data at the end.

**To Reproduce**
- Create a document template docx with a Table in it
- Create one line with static data for header
- Create one line with data and with repeatTableRow(youriterableobject) in a comment linked to this line
- Create one line with static data for footer.

**Expected behavior**
You need to keep the order of the lines around the iterative data

**Screenshots**
Template : 
![image](https://user-images.githubusercontent.com/640683/211581463-2e86fbf3-a5ca-4722-bd48-87a509b81f2b.png)

What I do expect : the last lines after the repeat data
![image](https://user-images.githubusercontent.com/640683/211581911-3fdf65d3-580c-46e4-a7ba-d2a3f837e158.png)

The result (wrong) : 
![image](https://user-images.githubusercontent.com/640683/211581623-9b0b7f4f-6506-46da-a38e-10ee7c8d4ea4.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Java version: [11, 17]
 - docx4j version: 11.4.8
 - docx-stamper version [
 8b20c1510ffc64fa22db127570e3c512449f12ae commit => Not good
 d7fd06cb012bb99114faa537e6ecae7b4ed6d089 commit => good
]

**Additional context**
No additional context.

**Comment by josephverron** [comment]
I believe that this bug has been fixed in branch master-javax, we are about to finally merge those branches together

**Comment by ynaciri** [comment]
should be solved by #129
