### ISSUE TITLE
Just wondering to know where is maven package locate?

### ISSUE THREAD

**Issue by jonaskahn** [verronpro/docx-stamper#222]
Hi folks,
I found your very interesting repo. I want to use this library but I can't find the maven repo to download. Could you please tell me the repo location ?

**Comment by caring-coder** [comment]
did you find it in the end ?

**Comment by jonaskahn** [comment]
So I actually deployed the library to my private maven repo :D

**Comment by caring-coder** [comment]
You can find it here in the future : https://mvnrepository.com/artifact/pro.verron/docx-stamper or https://central.sonatype.com/artifact/pro.verron/docx-stamper, and it should all be available as a standard in the central repos

**Comment by jonaskahn** [comment]
Oh I see. Thank you, mate.
