### ISSUE TITLE
Expression Replacements in single-line plain-text Form Controls

### ISSUE THREAD

**Issue by shimikano** [verronpro/docx-stamper#286]
Hello

First of all, thank you for keeping this project alive!

I noticed that expressions in single-line plain text form controls (Developer/Controls/Plain Text Content Control) are not replaced, while expressions in multi-line plain text form controls and rich text form controls are.

Presumably, the reason is that the single-line plain text form controls don't contain paragraphs.

Here's a test case based on `ExpressionReplacementInTextBoxesTest` reproducing the issue:

```java
class ExpressionReplacementInFormControlsTest {

  @Test
  void expressionsInFormControlsShouldBeReplaced() {
    var context = new Name("Bart Simpson");
    var template = getResource(Path.of("ExpressionReplacementInFormControlsTest" +
							 ".docx"));
    var stamper = new TestDocxStamper<Name>(new DocxStamperConfiguration());
    var actual = stamper.stampAndLoadAndExtract(template, context, P.class);

    var numberOfBartSimpsons = actual.stream().filter(it -> it.contains("Bart Simpson")).count();

    assertEquals(3, numberOfBartSimpsons); // there should be 2 replacements
  }

  private record Name(String name) {}

}
```

The template: [ExpressionReplacementInFormControlsTest.docx](https://github.com/verronpro/docx-stamper/files/15120081/ExpressionReplacementInFormControlsTest.docx)

Enabling multiple lines (in the Properties) for the form control is a workaround, but I was wondering whether this issue is known.

**Comment by shimikano** [comment]
Sorry for the noise - I realized that the test case I posted actually passes 🤦 In other words, all replacements work fine.

Since I definitely had cases where the replacement didn't work for single-line form controls, there must be certain circumstances where it doesn't work. However, I'm unable to reproduce them at the moment.

I'll close this issue for now and get back if I have more insight...

**Comment by shimikano** [comment]
For the sake of completeness: I dug a bit deeper and as expected, the reason why sometimes expression in form controls are not replaced is because they are not within a paragraph.

I managed to reproduce the issue in the edited test case and template in the original post.

The first form control works fine, since the `<w:sdtContent>` element contains a paragraph, which in turn contains the node with the expression to be replaced:

```xml
<w:sdtContent>
    <w:p w14:paraId="6DC384B1" w14:textId="63E3B9C5"> <!-- paragraph -->
        <w:r>
            <w:t>${name}</w:t>
        </w:r>
    </w:p>
</w:sdtContent>
```

However, the expression in the second form control is not replaced, since the `<w:sdtContent>` element does not contain a paragraph:

```xml
<w:sdtContent> <!-- no paragraph -->
    <w:r>
        <w:t>${name}</w:t>
    </w:r>
</w:sdtContent>
```

**Comment by caring-coder** [comment]
Good observation, I'll reopen the topic, and ponder on how to best integrate this case.

And no, we did not know about that case, the user base for this lib is not too big yet, while the feature set of Word is huge 😜

**Comment by caring-coder** [comment]
I added support for the simple cases of form controls in the 2.2 version, with some simple test case. Hopefully it solves most of your use case; and probably some other unknown case. Do not hesitate to make some feedback

**Comment by shimikano** [comment]
Using version >= 3.0, particularly 3.5, I came across placeholders in **form controls within tables** that are not replaced correctly during stamping.

To reproduce the issue, you can replace the existing `form-controls.docx` test file with [this one](https://github.com/user-attachments/files/29299967/form-controls.docx) and run the tests. The placeholder in the first table is _not_ replaced, whereas the placeholder in the second table is:

<img width="649" height="420" alt="Image" src="https://github.com/user-attachments/assets/8e1237fe-9818-46fb-a3f4-d508832af789" />

I am not sure what causes this difference or whether it is related to the observations above concerning paragraphs. The resulting text after stamping is of the same form as described in #775: `${name}` becomes `name` instead of `Homer`. This may indicate some overlap with the way text boxes are processed.

The same replacements worked correctly in my source documents with version 2.9.0, so this appears to be a regression introduced in version 3.0.

**Comment by caring-coder** [comment]
Thanks for the test case, I'll check this later today.

**Comment by caring-coder** [comment]
It is very likely that the engine expect to find a P inside a Cell, and instead it find an std content that it doesn't expect there.

**Comment by caring-coder** [comment]
Issue fixed, asciidoc updated to improve test readability. Wait for 3.6 deploy.

**Comment by shimikano** [comment]
Thank you very much! I can confirm this works fine now with 3.6.
