### ISSUE TITLE
Advice on integration testing with this library

### ISSUE THREAD

**Issue by StefanLobbenmeierObjego** [verronpro/docx-stamper#321]
**Is your feature request related to a problem? Please describe.**
In v1.6.7 I had integration tests with a method like this:

```kotlin
    private fun readFullDocument(documentData: ByteArray): List<String> {
        val document = WordprocessingMLPackage.load(documentData.inputStream())
        return document.mainDocumentPart.content.map { ParagraphWrapper(it as P).text }
    }
```

Since ParagraphWrapper was removed in 1.6.8 this no longer works. I think I originally copied this from the test sources. The Test sources now use a different method of checking the stamped document, which uses a lot of code from the test scope, so that no longer works

**Describe the solution you'd like**
An easy API to verify the content of the document

**Describe alternatives you've considered**
Copying the Stringifier and the TestDocxStamper from the Unit Tests in this repo

**Additional context**
I use this mostly to make sure there are no breaking changes in the upgrades and to verify my own TypeResolvers

**Comment by StefanLobbenmeierObjego** [comment]
Figured out another solution on my own, using TextUtils from the docx4j package. This is the new new version of that code:
```kotlin
    private fun readFullDocument(documentData: ByteArray): List<String> {
        val document = WordprocessingMLPackage.load(documentData.inputStream())
        return document.mainDocumentPart.content.map { TextUtils.getText(it as P) }
    }
```

**Comment by caring-coder** [comment]
Glad you found a simple solution, the Stringifier + Test docx-stamper are probably overkill for your needs indeed. 

The slow cleanup of the API means the "word as a string" features should slowly move to production scope one day or another, as a way to generate simple word templates directly from a string representation, but it's not my priority today.
