### ISSUE TITLE
Image rendering in repetition unreliable

### ISSUE THREAD

**Issue by mpressmar** [verronpro/docx-stamper#34]
First of all, thanks a lot for your work on the library, it's very appreciated.

We found an issue with image rendering within repetition comment sections in your version 1.4.6, which doesn't appear in Thomberg's release 1.0.2.
Image placeholders are replaced, but there's no image content rendered. Images outside of a repetition comment are rendered correctly.
I also found a strange effect: when placing one image outside the repetition block, and two or more images within the repetition comment, the second image is correctly rendered, the others are not.

I'm attaching a template (created with LibreOffice) and the stamper output.

[ImageTest.docx](https://github.com/verronpro/docx-stamper/files/9591091/ImageTest.docx)

[ImageTest_output.docx](https://github.com/verronpro/docx-stamper/files/9591092/ImageTest_output.docx)

**Comment by josephverron** [comment]
Peculiar, i'll take a look.

Do you know if thombergs version 1.4.0 also has the problem ?

**Comment by josephverron** [comment]
version 1.4.7 should have fixed the problem
