### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by t-oster** [verronpro/docx-stamper#35]
Hi,

first of all thank you for working on this project! The recursion is exactly the feature which is needed and all other improvements also.
Are you planning to publish this to maven central, so I can use the modified version without manual intervention?

**Comment by t-oster** [comment]
nevermind... found it.

**Comment by AJ1040273** [comment]
Yes, it's on maven central, on pro.verron.docx-stamper -> https://mvnrepository.com/artifact/pro.verron/docx-stamper

**Comment by t-oster** [comment]
Thanks for the quick answer. BTW are you planning to integrate furhter features? Mainly the replacement of text in text-boxes is very important for us https://github.com/thombergs/docx-stamper/issues/97. I already asked the developer to create a PR, but maybe you already looked at it.

**Comment by josephverron** [comment]
I am okay to integrate it, it's just not our team priority right now.
We'd have no reason to refuse a good PR with a covering test case, for this is a logical feature to implement for this library.
I'll work on a clear manifesto of what would be the wanted feature set.

**Comment by josephverron** [comment]
Usually i make it available in the followinghours, but it is a manual step i didn't automated yet.
I like to keep room for testing the new version with some existing applications first.
It should be available in the coming hour.

**Comment by StefanLobbenmeierObjego** [comment]
Thanks, its out now
