### ISSUE TITLE
Variables in text boxes do not get replaced

### ISSUE THREAD

**Issue by josephverron** [verronpro/docx-stamper#40]
_Originally posted by @t-oster in https://github.com/thombergs/docx-stamper/issues/97#issuecomment-1255465475_

**Comment by dallanmc** [comment]
I created a new pull request to show you how I had approached this issue. 
https://github.com/verronpro/docx-stamper/pull/48
As you can see there is actually less code in the new branch. I have got rid of some of the co-ordinates stuff, which I don't believe we need.
