### ISSUE TITLE
repeatTableRow with a Set stopped working in 1.6.2

### ISSUE THREAD

**Issue by mpressmar** [verronpro/docx-stamper#510]
**Describe the bug**
In Version 1.5.0 a SpEL expression returning a Set of elements could be used in combination with repeatTableRow. Starting from version 1.6.2 that's not possible anymore.

**To Reproduce**

Add a repeatTableRow(mySet) comment to a word document.
In my example, I'm using the entrySet of a map.

See the error:

Comment 'repeatTableRow(unitsByPropertyAndValue.entrySet())' failed to process. 

**Expected behavior**
I'd understand that the library became more strict about not accepting Sets where a List is expected by the Repeat processor, but I'd still like to get the old behaviour back to support legacy templates.

Is there any flag or extension I need to use?

**Comment by mpressmar** [comment]
After some debugging I can see that in 1.5.0 the ReflectiveMethodResolver was able to resolve the right repeatTableRow method because a proxy object was passed in. While testing with officestamper version 2.5.0 I see that the ReflectiveMethodResolver is still configured, but as we don't pass in the proxy anymore, there are no matching methods. The new StandardMethodResolver appears to be more strict about matching methods and won't resolve the repeatTableRow method unless the argument types are assignable (which they aren't, in the Set -> List case).

**Comment by mpressmar** [comment]
Would it be possible to change the repeatTableRow to accept a collection instead of a List? It only requires some type changes, as the only method we need to invoke on the List argument is `iterator` - which a java Collection has.
This would ensure backwards compatibility for these templates.

**Comment by caring-coder** [comment]
No issue with getting down to the lowest denominator on my side.
I'll make a new version quickly with this in mind.

Anyways, nothing stops you from creating your own Processor in the meantime as well.

**Comment by mpressmar** [comment]
Indeed - we'll patch the processor for the time being on our side, so no urgency :)
Thank you for taking it up for the next release, and for all your work on the library!
