### ISSUE TITLE
displayParagraphIf doesn't work inside table with repeatTableRow 

### ISSUE THREAD

**Issue by caring-coder** [verronpro/docx-stamper#52]
Is it still a problem ?

https://github.com/thombergs/docx-stamper/issues/24

**Comment by josephverron** [comment]
Yep, problem is still present. 
Working on a fix, it might imply a heavy rework on order of application of comment processing.

**Comment by caring-coder** [comment]
Created a branch with a test case

**Comment by caring-coder** [comment]
Well, reintroducing the test, it seems this issue is solved
