### ISSUE TITLE
Formatting is lost

### ISSUE THREAD

**Issue by josephverron** [verronpro/docx-stamper#59]
Do we still have this problem ?

copied from https://github.com/thombergs/docx-stamper/issues/64
copied from https://github.com/thombergs/docx-stamper/issues/67
copied from https://github.com/thombergs/docx-stamper/issues/68
copied from https://github.com/thombergs/docx-stamper/issues/73

**Comment by Tirex** [comment]
Confirming the problem. 'Font changing to Calibri 10'. Using the last 1.6.2 version.

**Comment by josephverron** [comment]
Yes, i would love a sample document, 

Even though i guess i could reproduce some cases on my side, i'm sure you can show some case we are not aware of yet

**Comment by josephverron** [comment]
Should be fixed in 1.6.3
