### ISSUE TITLE
Is there a unit test with a templating example ? Because when I try with 1.5.0 and 1.4.7 version, I don't succeed in recursive docPart ... the first level is ok, but inside, the loop doesn't seem to work.

### ISSUE THREAD

**Issue by AJ1040273** [verronpro/docx-stamper#99]
Is there a unit test with a templating example ? Because when I try with 1.5.0 and 1.4.7 version, I don't succeed in recursive docPart ... the first level is ok, but inside, the loop doesn't seem to work.

_Originally posted by @Kyoku57 in https://github.com/verronpro/docx-stamper/issues/2#issuecomment-1321941248_

**Comment by AJ1040273** [comment]
@ynaciri

**Comment by ynaciri** [comment]
Seems there is a PR adressing this exact use case, maybe you can check if it fits your need : https://github.com/verronpro/docx-stamper/pull/100

**Comment by Kyoku57** [comment]
I confirm that there is a test provided by the #100 ;-)
NOTE : The nested repeat works only for the repeatDocPart processor.

**Comment by ynaciri** [comment]
Lots of changes were made on repeatDocPart, hopefully this issue will be resolved by #129

**Comment by josephverron** [comment]
Example of nesting is given here -> https://github.com/verronpro/docx-stamper/blob/master/src/test/resources/org/wickedsource/docxstamper/RepeatDocPartNestingTest.docx
